### ISSUE TITLE
Does the network do Classification?

### ISSUE THREAD

**Issue by hz3014** [PRBonn/rangenet_lib#10]
Hey, I noticed the RangeNet segments obstacles into different colors ie. vehicle in ink blue, road in pink, barrier in orange. As I did not find anything about classification in the paper, I was wondering if this network do point cloud classification?

**Comment by jbehley** [comment]
Hi,

we are doing the closely related "semantic segmentation", where we assign each point a distinct label. Therefore, we do something like "point-wise" classification. (The loss is actually cross-entropy, i.e., a classification loss.)
