### ISSUE TITLE
Computation of image means and standard deviations

### ISSUE THREAD

**Issue by joelloo** [PRBonn/rangenet_lib#17]
Hi,

Thanks for making this state of the art algorithm readily available!

When experimenting with your code, I noticed that you provide in your config file image mean and standard deviation parameters. I presume that this is to normalise the image/vertex map that we are passing to the network. I'm curious if these values are computed in the standard way, and using solely the SemanticKITTI training and validation data?

Thanks for your help!

**Comment by tano297** [comment]
Yes, these values are calculated from the training sequences of semanticKitti (sequences 00 to 10, not including 8), like in the [original paper](http://www.ipb.uni-bonn.de/wp-content/papercite-data/pdf/milioto2019iros.pdf)
