### ISSUE TITLE
Inference preprocessing 

### ISSUE THREAD

**Issue by abhigoku10** [PRBonn/rangenet_lib#25]
@niosus @stachnis @jbehley @Chen-Xieyuanli @ovysotska  Hi thanks for sharing the library of rangenet i was able to build it on my system . i have folllowing queries 

1. i am able to run the library on the semanttic and obtain right output but when i run the model on custom dataset / other source dataset i get only red presentation of the point cloud 
2.how to obtain the list of classes predicted from the model from the inference code
3.can we get the location of the predicted objects or draw cuboids around them
THanks in advance

**Comment by Chen-Xieyuanli** [comment]
Hey @abhigoku10,

SuMa++ and rangenet_lib currently only work with the KITTI dataset. For more possible applications of rangenet++ you may have a look at [LiDAR-bonnetal](https://github.com/PRBonn/lidar-bonnetal).

I noticed that you already raise the same there, I will therefore close this issue.
