### ISSUE TITLE
How to use knn post-processing in this demo?

### ISSUE THREAD

**Issue by ONMEKEEP** [PRBonn/rangenet_lib#27]
Hi. I want to know how can I use knn post-processing in this demo. I have changed the boolean value to True in the arch_cfg.yaml file parameter, but it doesn't works. Could you give me some advice?

**Comment by Chen-Xieyuanli** [comment]
Hi @ONMEKEEP,

The knn post-processing will not be offered in the inference pipeline. 

Since this issue is duplicated to #16, I'm going to close it.
