### ISSUE TITLE
Inference on .pcd file format

### ISSUE THREAD

**Issue by Ewaolx** [PRBonn/rangenet_lib#3]
Hi,

Thanks for this amazing work. 
I was wondering is it possible to infer on a lidar scan in .pcd file format?
Thanks.

**Comment by Chen-Xieyuanli** [comment]
Sorry for the late reply.

This repo is only an example library for our SuMa++, semantic LiDAR SLAM, which is now only available with the KITTI dataset format. We currently don't have a plan to use other formats.

We will later release a full C++ develop repo for RangeNet++, which may be available for more formats of LiDAR scans.

**Comment by Ewaolx** [comment]
Alright. Thanks for the reply.
