### ISSUE TITLE
could not parse own input ONNX.

### ISSUE THREAD

**Issue by xdtzzz** [PRBonn/rangenet_lib#38]
hi, thx for your amazing codes.
when i trained my own dataset using your (https://github.com/PRBonn/lidar-bonnetal) , i got a file, like this.
![屏幕截图 2021-06-07 15:44:11](https://user-images.githubusercontent.com/82450947/120980014-bc266c80-c7a8-11eb-9129-61944ec993d7.png)

and then i change it to a model.onnx,   then i want to use rangenet_lib to check my train performence, but a problem happens, like this.
![图片](https://user-images.githubusercontent.com/82450947/120980451-35be5a80-c7a9-11eb-8494-2d749dc967c0.png)
![图片](https://user-images.githubusercontent.com/82450947/120980470-39ea7800-c7a9-11eb-803e-702eb60b1162.png)
it seems that there is a problem in model.onnx.
can you help me? thanks in advance!!!

**Comment by Chen-Xieyuanli** [comment]
Hi @xdtzzz, this issue is quite similar to #26. Could you please first have a look there?

Since this is duplicated to #26, I would like to close this one to better track the same issue.

**Comment by xdtzzz** [comment]
thanks for your reply so quickly.
but my problem is different to that.
that question is test a demo on your trained model, but my question is on my own trained model.
i can test it successfully on your trained model, but cannot work on my own.
