### ISSUE TITLE
why should use sort?

### ISSUE THREAD

**Issue by longzeyilang** [PRBonn/rangenet_lib#42]
https://github.com/PRBonn/rangenet_lib/blob/91bde5a99245975befe65eb57088d536b9ed8fcb/src/netTensorRT.cpp#L177

I do not think it must use the sort. would you explain?

**Comment by Chen-Xieyuanli** [comment]
Hey @longzeyilang, thanks for using our code. 

We use sort to keep only the nearest point to the sensor if several points are projected into the same range image pixel. Thus, the sort is needed.

I hope my answer is clear and helpful.

**Comment by longzeyilang** [comment]
Thank you for your replay.  I use cuda to accelerate, and not use sort. The test results are consistent.
