### ISSUE TITLE
The detection effect is not good when object approaching vehicle

### ISSUE THREAD

**Issue by longzeyilang** [PRBonn/rangenet_lib#43]
I send some detection images to github. https://github.com/longzeyilang/fast-range-net-plus-plus
I can not find the reasons.

**Comment by Chen-Xieyuanli** [comment]
Hey @longzeyilang thanks for using our code. 

Rangenet++ was evaluated on 64-beam lidar data from KITTI, which may not work well with other types of data.

For own collected data, you may need to train the model again.
