### ISSUE TITLE
Is there a requirement for the number of radar lines?

### ISSUE THREAD

**Issue by hanbing123-cool** [PRBonn/rangenet_lib#44]
Is there a requirement for the number of radar lines? I got poor results with 16-line lidar, but I got good results with data sets.

**Comment by Chen-Xieyuanli** [comment]
Hey @hanbing123-cool, thanks for using our code. 

Rangenet++ was evaluated on 64-beam lidar data from KITTI, which may not work well with other types of data.

For your own-collected data, you may need to train the model again.
