### ISSUE TITLE
Failure creating engine from ONNX model

### ISSUE THREAD

**Issue by xdtzzz** [PRBonn/rangenet_lib#45]
Hi, thanks for your coding.
When I run rangenet++ with model.onnx, I will meet this problem, so that the result of model.trt is not correct. I have trained my own dataset, the prediction is correct, but when run rangenet++, it is wrong.
It shows that ----- Parsing of ONNX model /home/xdt/logs/log8///model.onnx is Done ---- 
Success picking up ONNX model
Failure creating engine from ONNX model
Current trial size is 8589934592
Failure creating engine from ONNX model
Current trial size is 4294967296
Failure creating engine from ONNX model
Current trial size is 2147483648
Success creating engine from ONNX model
Final size is 1073741824
Success creating engine from ONNX model
![2022-01-12 15-02-23 的屏幕截图](https://user-images.githubusercontent.com/82450947/149081588-1cb2e4a3-2837-4f44-99cf-b87c360cb2bb.png)

**Comment by Chen-Xieyuanli** [comment]
That's a GPU memory issue, and you may need a GPU with larger memory.
