### ISSUE TITLE
Speed on Jetson AGX

### ISSUE THREAD

**Issue by mc171819** [PRBonn/rangenet_lib#46]
Hi, it's a wonderful work. I found the speed of 64x2048 is 5 fps in your paper. However I wonder how's the speed on Jetson AGX of rangenet++ after tensorrt speed up? @Chen-Xieyuanli

**Comment by Chen-Xieyuanli** [comment]
Hey @mc171819, thanks for your interest in our method and using our code. 

However, I'm not the author of RangeNet++. You may send an email directly to Andres (https://andres.milioto.me/) or raise an issue in the original repo (https://github.com/PRBonn/lidar-bonnetal).
