### ISSUE TITLE
How to generate model.onnx like your provide   pre-trained model file 

### ISSUE THREAD

**Issue by Zhangjyhhh** [PRBonn/rangenet_lib#57]
thanks for your excellent work!!!!!
i use rangent++ to train model, but there no model.onnx. And in your provide pre-train model file ,there is a model.onnx. I want to konw how to generate onnx

**Comment by Zhangjyhhh** [comment]
i have know how to do it

**Comment by Zhou-Ziheng-HIT** [comment]
> i have know how to do it

Hello, could you tell me how to get the model onnx?Thank you!
